"""initials

Revision ID: 2226d0adbef8
Revises: 
Create Date: 2026-03-08 17:49:18.342868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2226d0adbef8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backgrounds',
    sa.Column('bg_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bg_url', sa.Text(), nullable=False),
    sa.Column('bg_name', sa.String(length=100), nullable=False),
    sa.Column('bg_lore', sa.Text(), nullable=True),
    sa.Column('bg_cost', sa.Integer(), nullable=False),
    sa.Column('bg_rarity', sa.String(length=20), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('bg_id')
    )
    op.create_table('heroes',
    sa.Column('hero_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hero_image', sa.Text(), nullable=False),
    sa.Column('hero_tier', sa.String(length=20), nullable=False),
    sa.Column('hero_lore', sa.Text(), nullable=True),
    sa.Column('hero_attack', sa.Integer(), nullable=False),
    sa.Column('hero_specialattack', sa.Integer(), nullable=False),
    sa.Column('hero_defence', sa.Integer(), nullable=False),
    sa.Column('hero_specialdefence', sa.Integer(), nullable=False),
    sa.Column('hero_speed', sa.Integer(), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('hero_id')
    )
    op.create_table('users',
    sa.Column('uid', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('username')
    )
    op.create_table('choronux',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_backgrounds',
    sa.Column('user_bg_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('bg_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bg_id'], ['backgrounds.bg_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_bg_id')
    )
    op.create_table('user_heroes',
    sa.Column('user_hero_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('hero_id', sa.Integer(), nullable=False),
    sa.Column('hero_attack', sa.Integer(), nullable=False),
    sa.Column('hero_specialattack', sa.Integer(), nullable=False),
    sa.Column('hero_defence', sa.Integer(), nullable=False),
    sa.Column('hero_specialdefence', sa.Integer(), nullable=False),
    sa.Column('hero_speed', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hero_id'], ['heroes.hero_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_hero_id')
    )
    op.create_table('vault',
    sa.Column('vauld_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('user_hero_id', sa.Integer(), nullable=True),
    sa.Column('user_bg_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_bg_id'], ['user_backgrounds.user_bg_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_hero_id'], ['user_heroes.user_hero_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vauld_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vault')
    op.drop_table('user_heroes')
    op.drop_table('user_backgrounds')
    op.drop_table('choronux')
    op.drop_table('users')
    op.drop_table('heroes')
    op.drop_table('backgrounds')
    # ### end Alembic commands ###
