"""add hero_name

Revision ID: 85af95f10b94
Revises: 2226d0adbef8
Create Date: 2026-03-09 20:42:12.648621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85af95f10b94'
down_revision: Union[str, Sequence[str], None] = '2226d0adbef8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('heroes', sa.Column('hero_name', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('heroes', 'hero_name')
    # ### end Alembic commands ###
